### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by st0ffern** [doubleqliq/react-native-view-editor#1]
https://github.com/stoffern/react-native-image-cropper

**Comment by sscaff1** [comment]
@stoffern Looks really cool. Thanks for sharing with me. Mine is meant to restrict the resizing an panning in it's containing view (similar to instagram or twitter when adding a photo), but it doesn't crop like yours does. I don't know if that's the purpose of your package. If it is, I can submit a PR to combine our libraries.

**Comment by st0ffern** [comment]
@sscaff1 if you disable zoom or set it to 1 your effect is already there... ;)

**Comment by sscaff1** [comment]
@stoffern Have you played around with my component? You can set a mask over the image and the image will actually bounce (animated) back out to fit the width of the mask. Or if you pan beyond the the limits of the  mask it'll snap back into the place. That's why there is so much logic in my component.

**Comment by sscaff1** [comment]
That's why I'm cloning the child in the component so I can pass it the animated width and height since I can't flex a GL surface.
